### ISSUE TITLE
Line 251 error

### ISSUE THREAD

**Issue by DianixGTX** [reliactyldev/Reliactyl-2.0#1]
ReferenceError: ./frontend/pages/servers.ejs:251
    249|                                                                                                                     ) {
    250|                                                                                                                     %>
 >> 251|                                                                                                                     <% //
    252|                                                                                                                         https://stackoverflow.com/questions/9763441/milliseconds-to-time-in-javascript
    253|                                                                                                                         let
    254|                                                                                                                         s=server_timers[server.attributes.id].timer

let is not defined
    at eval (eval at compile (/root/Reliactyl-2.0/node_modules/ejs/lib/ejs.js:673:12), <anonymous>:154:121)
    at servers (/root/Reliactyl-2.0/node_modules/ejs/lib/ejs.js:703:17)
    at tryHandleCache (/root/Reliactyl-2.0/node_modules/ejs/lib/ejs.js:274:36)
    at Object.exports.renderFile (/root/Reliactyl-2.0/node_modules/ejs/lib/ejs.js:491:10)
    at /root/Reliactyl-2.0/handlers/pages.js:157:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  path: './frontend/pages/servers.ejs'
}

**Comment by rcong9** [comment]
thanks u for reposing, i fixed it
